local M = {}

M.colors = {
	none = "NONE",
	background = "#24202C",
	surface = "#2F293A",
	raised = "#393143",
	foreground = "#F4CDE9",
	muted = "#AD7FA8",
	cursor = "#E9897C",
	selection = "#5A4551",
	accent = "#B6377D",

	black = "#050505",
	red = "#E9897C",
	ansi_green = "#B6377D",
	yellow = "#ECEBBE",
	blue = "#A9CDEB",
	magenta = "#75507B",
	cyan = "#C9CAEC",
	white = "#F2F2F2",

	bright_black = "#141414",
	bright_red = "#F99286",
	bright_green = "#C3F786",
	bright_yellow = "#FCFBCC",
	bright_blue = "#B6DEFB",
	bright_magenta = "#AD7FA8",
	bright_cyan = "#D7D9FC",
	bright_white = "#E2E2E2",

	diff_add = "#34412E",
	diff_remove = "#493039",
}

local function set_terminal_colors(c)
	local colors = {
		c.black,
		c.red,
		c.ansi_green,
		c.yellow,
		c.blue,
		c.magenta,
		c.cyan,
		c.white,
		c.bright_black,
		c.bright_red,
		c.bright_green,
		c.bright_yellow,
		c.bright_blue,
		c.bright_magenta,
		c.bright_cyan,
		c.bright_white,
	}

	for index, color in ipairs(colors) do
		vim.g["terminal_color_" .. index - 1] = color
	end
end

function M.setup()
	local c = M.colors
	local set_hl = vim.api.nvim_set_hl

	vim.cmd("highlight clear")
	if vim.fn.exists("syntax_on") == 1 then
		vim.cmd("syntax reset")
	end
	vim.o.background = "dark"
	vim.o.termguicolors = true
	vim.g.colors_name = "orchid-dark"
	set_terminal_colors(c)

	local highlights = {
		Normal = { fg = c.foreground, bg = c.none },
		NormalNC = { fg = c.foreground, bg = c.none },
		NormalFloat = { fg = c.foreground, bg = c.raised },
		FloatBorder = { fg = c.selection, bg = c.raised },
		FloatTitle = { fg = c.accent, bg = c.raised, bold = true },
		Cursor = { fg = c.background, bg = c.cursor },
		CursorIM = { link = "Cursor" },
		CursorColumn = { bg = c.surface },
		CursorLine = { bg = c.surface },
		CursorLineNr = { fg = c.accent, bg = c.surface, bold = true },
		LineNr = { fg = c.muted, bg = c.none },
		SignColumn = { fg = c.muted, bg = c.none },
		FoldColumn = { fg = c.muted, bg = c.none },
		Folded = { fg = c.muted, bg = c.surface },
		ColorColumn = { bg = c.surface },
		Visual = { fg = c.foreground, bg = c.selection },
		VisualNOS = { link = "Visual" },
		Search = { fg = c.background, bg = c.yellow, bold = true },
		IncSearch = { fg = c.background, bg = c.red, bold = true },
		CurSearch = { fg = c.background, bg = c.bright_red, bold = true },
		Substitute = { fg = c.background, bg = c.accent, bold = true },
		MatchParen = { fg = c.background, bg = c.cyan, bold = true },
		Pmenu = { fg = c.foreground, bg = c.raised },
		PmenuSel = { fg = c.foreground, bg = c.accent, bold = true },
		PmenuSbar = { bg = c.surface },
		PmenuThumb = { bg = c.selection },
		PmenuMatch = { fg = c.red, bg = c.raised, bold = true },
		PmenuMatchSel = { fg = c.yellow, bg = c.accent, bold = true },
		WildMenu = { fg = c.foreground, bg = c.accent, bold = true },
		StatusLine = { fg = c.foreground, bg = c.surface },
		StatusLineNC = { fg = c.muted, bg = c.none },
		WinSeparator = { fg = c.selection, bg = c.none },
		VertSplit = { link = "WinSeparator" },
		TabLine = { fg = c.muted, bg = c.surface },
		TabLineSel = { fg = c.foreground, bg = c.raised, bold = true, underline = true, sp = c.accent },
		TabLineFill = { bg = c.none },
		Title = { fg = c.red, bold = true },
		Directory = { fg = c.blue, bold = true },
		Question = { fg = c.bright_green },
		MoreMsg = { fg = c.bright_green },
		ModeMsg = { fg = c.accent, bold = true },
		ErrorMsg = { fg = c.red, bold = true },
		WarningMsg = { fg = c.yellow, bold = true },
		NonText = { fg = c.selection },
		SpecialKey = { fg = c.selection },
		Whitespace = { fg = c.selection },
		EndOfBuffer = { fg = c.background },
		Conceal = { fg = c.muted },
		QuickFixLine = { fg = c.foreground, bg = c.surface, bold = true },
		qfLineNr = { fg = c.blue },
		MsgArea = { fg = c.foreground, bg = c.none },
		MsgSeparator = { fg = c.selection, bg = c.surface },

		Comment = { fg = c.muted, italic = true },
		Constant = { fg = c.red },
		String = { fg = c.yellow },
		Character = { fg = c.yellow },
		Number = { fg = c.red },
		Boolean = { fg = c.bright_red },
		Float = { fg = c.red },
		Identifier = { fg = c.foreground },
		Function = { fg = c.blue },
		Statement = { fg = c.accent },
		Conditional = { fg = c.accent },
		Repeat = { fg = c.accent },
		Label = { fg = c.bright_magenta },
		Operator = { fg = c.foreground },
		Keyword = { fg = c.accent },
		Exception = { fg = c.red },
		PreProc = { fg = c.bright_magenta },
		Include = { fg = c.accent },
		Define = { fg = c.bright_magenta },
		Macro = { fg = c.bright_magenta },
		PreCondit = { fg = c.bright_magenta },
		Type = { fg = c.cyan },
		StorageClass = { fg = c.cyan },
		Structure = { fg = c.cyan },
		Typedef = { fg = c.cyan },
		Special = { fg = c.bright_magenta },
		SpecialChar = { fg = c.cyan },
		Tag = { fg = c.accent },
		Delimiter = { fg = c.muted },
		Debug = { fg = c.red },
		Underlined = { fg = c.blue, underline = true },
		Ignore = { fg = c.muted },
		Error = { fg = c.red, bg = c.diff_remove, bold = true },
		Todo = { fg = c.yellow, bold = true },

		Added = { fg = c.bright_green },
		Changed = { fg = c.blue },
		Removed = { fg = c.red },
		DiffAdd = { fg = c.bright_green, bg = c.diff_add },
		DiffChange = { fg = c.blue, bg = c.raised },
		DiffDelete = { fg = c.red, bg = c.diff_remove },
		DiffText = { fg = c.background, bg = c.blue, bold = true },

		DiagnosticError = { fg = c.red },
		DiagnosticWarn = { fg = c.yellow },
		DiagnosticInfo = { fg = c.cyan },
		DiagnosticHint = { fg = c.blue },
		DiagnosticOk = { fg = c.bright_green },
		DiagnosticUnderlineError = { sp = c.red, undercurl = true },
		DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
		DiagnosticUnderlineInfo = { sp = c.cyan, undercurl = true },
		DiagnosticUnderlineHint = { sp = c.blue, undercurl = true },
		DiagnosticUnderlineOk = { sp = c.bright_green, undercurl = true },
		DiagnosticVirtualTextError = { link = "DiagnosticError" },
		DiagnosticVirtualTextWarn = { link = "DiagnosticWarn" },
		DiagnosticVirtualTextInfo = { link = "DiagnosticInfo" },
		DiagnosticVirtualTextHint = { link = "DiagnosticHint" },
		DiagnosticVirtualTextOk = { link = "DiagnosticOk" },
		DiagnosticFloatingError = { link = "DiagnosticError" },
		DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
		DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
		DiagnosticFloatingHint = { link = "DiagnosticHint" },
		DiagnosticFloatingOk = { link = "DiagnosticOk" },
		DiagnosticSignError = { link = "DiagnosticError" },
		DiagnosticSignWarn = { link = "DiagnosticWarn" },
		DiagnosticSignInfo = { link = "DiagnosticInfo" },
		DiagnosticSignHint = { link = "DiagnosticHint" },
		DiagnosticSignOk = { link = "DiagnosticOk" },
		DiagnosticDeprecated = { fg = c.muted, strikethrough = true },
		DiagnosticUnnecessary = { fg = c.muted },
		SpellBad = { sp = c.red, undercurl = true },
		SpellCap = { sp = c.blue, undercurl = true },
		SpellLocal = { sp = c.cyan, undercurl = true },
		SpellRare = { sp = c.bright_magenta, undercurl = true },

		LspReferenceText = { bg = c.surface },
		LspReferenceRead = { bg = c.surface },
		LspReferenceWrite = { bg = c.surface, underline = true, sp = c.accent },
		LspInlayHint = { fg = c.muted, bg = c.surface, italic = true },
		LspCodeLens = { fg = c.muted, italic = true },
		LspSignatureActiveParameter = { fg = c.accent, bold = true, underline = true },

		["@comment"] = { link = "Comment" },
		["@comment.todo"] = { link = "Todo" },
		["@constant"] = { fg = c.red },
		["@constant.builtin"] = { fg = c.bright_red, italic = true },
		["@module"] = { fg = c.cyan },
		["@label"] = { fg = c.bright_magenta },
		["@string"] = { fg = c.yellow },
		["@string.escape"] = { fg = c.cyan, bold = true },
		["@string.special"] = { fg = c.cyan },
		["@character"] = { fg = c.yellow },
		["@boolean"] = { fg = c.bright_red },
		["@number"] = { fg = c.red },
		["@type"] = { fg = c.cyan },
		["@type.builtin"] = { fg = c.cyan, italic = true },
		["@attribute"] = { fg = c.bright_magenta },
		["@property"] = { fg = c.cyan },
		["@function"] = { fg = c.blue },
		["@function.builtin"] = { fg = c.bright_blue },
		["@function.call"] = { fg = c.blue },
		["@function.method"] = { fg = c.blue },
		["@function.method.call"] = { fg = c.blue },
		["@constructor"] = { fg = c.cyan },
		["@operator"] = { fg = c.foreground },
		["@keyword"] = { fg = c.accent },
		["@keyword.function"] = { fg = c.accent, italic = true },
		["@keyword.operator"] = { fg = c.accent },
		["@keyword.return"] = { fg = c.accent, italic = true },
		["@variable"] = { fg = c.foreground },
		["@variable.builtin"] = { fg = c.red, italic = true },
		["@variable.parameter"] = { fg = c.foreground, italic = true },
		["@variable.member"] = { fg = c.cyan },
		["@punctuation.delimiter"] = { fg = c.muted },
		["@punctuation.bracket"] = { fg = c.foreground },
		["@punctuation.special"] = { fg = c.accent },
		["@markup.heading"] = { fg = c.red, bold = true },
		["@markup.heading.1.markdown"] = { fg = c.red, bold = true },
		["@markup.heading.2.markdown"] = { fg = c.accent, bold = true },
		["@markup.heading.3.markdown"] = { fg = c.red, bold = true },
		["@markup.heading.4.markdown"] = { fg = c.accent, bold = true },
		["@markup.heading.5.markdown"] = { fg = c.red, bold = true },
		["@markup.heading.6.markdown"] = { fg = c.accent, bold = true },
		["@markup.link"] = { fg = c.blue },
		["@markup.link.label"] = { fg = c.blue, underline = true },
		["@markup.link.url"] = { fg = c.cyan, underline = true },
		["@markup.raw"] = { fg = c.cyan },
		["@markup.quote"] = { fg = c.muted, italic = true },
		["@markup.strong"] = { fg = c.foreground, bold = true },
		["@markup.italic"] = { fg = c.foreground, italic = true },
		["@markup.list.checked"] = { fg = c.bright_green },
		["@markup.list.unchecked"] = { fg = c.muted },
		["@diff.plus"] = { fg = c.bright_green },
		["@diff.delta"] = { fg = c.blue },
		["@diff.minus"] = { fg = c.red },
		["@tag"] = { fg = c.accent },
		["@tag.attribute"] = { fg = c.yellow },
		["@tag.delimiter"] = { fg = c.muted },

		markdownH1 = { fg = c.red, bold = true },
		markdownH2 = { fg = c.accent, bold = true },
		markdownH3 = { fg = c.red, bold = true },
		markdownH4 = { fg = c.accent, bold = true },
		markdownH5 = { fg = c.red, bold = true },
		markdownH6 = { fg = c.accent, bold = true },
		markdownLinkText = { fg = c.blue, underline = true },
		markdownUrl = { fg = c.cyan, underline = true },
		markdownCode = { fg = c.cyan },

		TelescopeNormal = { fg = c.foreground, bg = c.none },
		TelescopeBorder = { fg = c.selection, bg = c.none },
		TelescopePromptNormal = { fg = c.foreground, bg = c.none },
		TelescopePromptBorder = { fg = c.accent, bg = c.none },
		TelescopePromptPrefix = { fg = c.accent, bg = c.none },
		TelescopePromptTitle = { fg = c.accent, bg = c.none, bold = true },
		TelescopeResultsNormal = { fg = c.foreground, bg = c.none },
		TelescopeResultsBorder = { fg = c.selection, bg = c.none },
		TelescopePreviewNormal = { fg = c.foreground, bg = c.none },
		TelescopePreviewBorder = { fg = c.selection, bg = c.none },
		TelescopeSelection = { fg = c.foreground, bg = c.selection, bold = true },
		TelescopeSelectionCaret = { fg = c.accent, bg = c.selection, bold = true },
		TelescopeMatching = { fg = c.red, bold = true },
		TelescopeTitle = { fg = c.foreground, bg = c.none, bold = true },

		NeoTreeNormal = { fg = c.foreground, bg = c.none },
		NeoTreeNormalNC = { fg = c.foreground, bg = c.none },
		NeoTreeCursorLine = { bg = c.surface },
		NeoTreeDirectoryName = { fg = c.blue },
		NeoTreeDirectoryIcon = { fg = c.blue },
		NeoTreeFileName = { fg = c.foreground },
		NeoTreeFileNameOpened = { fg = c.cyan, bold = true },
		NeoTreeFileIcon = { fg = c.cyan },
		NeoTreeRootName = { fg = c.accent, bold = true },
		NeoTreeGitAdded = { fg = c.bright_green },
		NeoTreeGitConflict = { fg = c.red, bold = true },
		NeoTreeGitDeleted = { fg = c.red },
		NeoTreeGitIgnored = { fg = c.muted },
		NeoTreeGitModified = { fg = c.yellow },
		NeoTreeGitRenamed = { fg = c.cyan },
		NeoTreeGitStaged = { fg = c.bright_green },
		NeoTreeGitUnstaged = { fg = c.yellow },
		NeoTreeGitUntracked = { fg = c.bright_green },
		NeoTreeModified = { fg = c.yellow },
		NeoTreeDimText = { fg = c.muted },
		NeoTreeIndentMarker = { fg = c.selection },
		NeoTreeExpander = { fg = c.muted },
		NeoTreeFilterTerm = { fg = c.accent, bold = true },
		NeoTreeFloatNormal = { fg = c.foreground, bg = c.raised },
		NeoTreeFloatBorder = { fg = c.accent, bg = c.raised },
		NeoTreeSymbolicLinkTarget = { fg = c.cyan },
		NeoTreeTabActive = { fg = c.foreground, bg = c.surface, bold = true },
		NeoTreeTabInactive = { fg = c.muted, bg = c.none },
		NeoTreeTabSeparatorActive = { fg = c.accent, bg = c.surface },
		NeoTreeTabSeparatorInactive = { fg = c.selection, bg = c.none },
		NeoTreeWinSeparator = { fg = c.selection, bg = c.none },

		RenderMarkdownH1 = { fg = c.red, bold = true },
		RenderMarkdownH2 = { fg = c.accent, bold = true },
		RenderMarkdownH3 = { fg = c.red, bold = true },
		RenderMarkdownH4 = { fg = c.accent, bold = true },
		RenderMarkdownH5 = { fg = c.red, bold = true },
		RenderMarkdownH6 = { fg = c.accent, bold = true },
		RenderMarkdownH1Bg = { fg = c.red, bg = c.surface, bold = true },
		RenderMarkdownH2Bg = { fg = c.accent, bg = c.surface, bold = true },
		RenderMarkdownH3Bg = { fg = c.red, bg = c.surface, bold = true },
		RenderMarkdownH4Bg = { fg = c.accent, bg = c.surface, bold = true },
		RenderMarkdownH5Bg = { fg = c.red, bg = c.surface, bold = true },
		RenderMarkdownH6Bg = { fg = c.accent, bg = c.surface, bold = true },
		RenderMarkdownCode = { fg = c.cyan, bg = c.surface },
		RenderMarkdownCodeInline = { fg = c.cyan, bg = c.surface },
		RenderMarkdownLink = { fg = c.blue },
		RenderMarkdownChecked = { fg = c.bright_green },
		RenderMarkdownUnchecked = { fg = c.muted },
		RenderMarkdownWarn = { fg = c.yellow },
		RenderMarkdownBullet = { fg = c.accent },
		RenderMarkdownTableHead = { fg = c.yellow },
		RenderMarkdownTableRow = { fg = c.selection },

		CmpItemAbbr = { fg = c.foreground },
		CmpItemAbbrDeprecated = { fg = c.muted, strikethrough = true },
		CmpItemAbbrMatch = { fg = c.red, bold = true },
		CmpItemAbbrMatchFuzzy = { fg = c.accent, bold = true },
		CmpItemMenu = { fg = c.muted },
		CmpItemKindText = { fg = c.foreground },
		CmpItemKindMethod = { fg = c.blue },
		CmpItemKindFunction = { fg = c.blue },
		CmpItemKindConstructor = { fg = c.cyan },
		CmpItemKindField = { fg = c.cyan },
		CmpItemKindVariable = { fg = c.foreground },
		CmpItemKindClass = { fg = c.cyan },
		CmpItemKindInterface = { fg = c.cyan },
		CmpItemKindModule = { fg = c.bright_magenta },
		CmpItemKindProperty = { fg = c.cyan },
		CmpItemKindUnit = { fg = c.yellow },
		CmpItemKindValue = { fg = c.red },
		CmpItemKindEnum = { fg = c.cyan },
		CmpItemKindKeyword = { fg = c.accent },
		CmpItemKindSnippet = { fg = c.bright_magenta },
		CmpItemKindColor = { fg = c.red },
		CmpItemKindFile = { fg = c.blue },
		CmpItemKindReference = { fg = c.cyan },
		CmpItemKindFolder = { fg = c.blue },
		CmpItemKindEnumMember = { fg = c.red },
		CmpItemKindConstant = { fg = c.red },
		CmpItemKindStruct = { fg = c.cyan },
		CmpItemKindEvent = { fg = c.red },
		CmpItemKindOperator = { fg = c.foreground },
		CmpItemKindTypeParameter = { fg = c.cyan },

		NoiceCmdlinePopup = { fg = c.foreground, bg = c.raised },
		NoiceCmdlinePopupBorder = { fg = c.accent, bg = c.raised },
		NoiceCmdlinePopupBorderSearch = { fg = c.red, bg = c.raised },
		NoiceCmdlineIcon = { fg = c.accent },
		NoiceCmdlineIconSearch = { fg = c.red },
		NoicePopup = { fg = c.foreground, bg = c.raised },
		NoicePopupBorder = { fg = c.selection, bg = c.raised },
		NoicePopupmenu = { fg = c.foreground, bg = c.raised },
		NoicePopupmenuSelected = { fg = c.foreground, bg = c.selection, bold = true },
		NoiceConfirm = { fg = c.foreground, bg = c.raised },
		NoiceConfirmBorder = { fg = c.accent, bg = c.raised },

		NotifyERRORBorder = { fg = c.red, bg = c.raised },
		NotifyERRORIcon = { fg = c.red },
		NotifyERRORTitle = { fg = c.red, bold = true },
		NotifyWARNBorder = { fg = c.yellow, bg = c.raised },
		NotifyWARNIcon = { fg = c.yellow },
		NotifyWARNTitle = { fg = c.yellow, bold = true },
		NotifyINFOBorder = { fg = c.cyan, bg = c.raised },
		NotifyINFOIcon = { fg = c.cyan },
		NotifyINFOTitle = { fg = c.cyan, bold = true },
		NotifyDEBUGBorder = { fg = c.muted, bg = c.raised },
		NotifyDEBUGIcon = { fg = c.muted },
		NotifyDEBUGTitle = { fg = c.muted, bold = true },
		NotifyTRACEBorder = { fg = c.bright_magenta, bg = c.raised },
		NotifyTRACEIcon = { fg = c.bright_magenta },
		NotifyTRACETitle = { fg = c.bright_magenta, bold = true },

		BufferLineFill = { bg = c.none },
		BufferLineBackground = { fg = c.muted, bg = c.none },
		BufferLineBufferSelected = { fg = c.foreground, bg = c.surface, bold = true },
		BufferLineIndicatorSelected = { fg = c.accent, bg = c.surface },
		BufferLineSeparator = { fg = c.background, bg = c.none },
		BufferLineSeparatorSelected = { fg = c.accent, bg = c.surface },
		BufferLineModified = { fg = c.yellow, bg = c.none },
		BufferLineModifiedSelected = { fg = c.yellow, bg = c.surface },
		BufferLineError = { fg = c.red, bg = c.none },
		BufferLineErrorSelected = { fg = c.red, bg = c.surface },

		StartifyHeader = { fg = c.accent, bold = true },
		StartifyFile = { fg = c.foreground },
		StartifyPath = { fg = c.muted },
		StartifyNumber = { fg = c.red },
		StartifyBracket = { fg = c.selection },
		StartifySpecial = { fg = c.cyan },
		StartifySlash = { fg = c.selection },
		StartifySection = { fg = c.yellow, bold = true },
		StartifyFooter = { fg = c.muted },
		OrchidAccent = { fg = c.accent, bold = true },
	}

	for group, styles in pairs(highlights) do
		set_hl(0, group, styles)
	end
end

return M
